server:
  port: 8040
spring:
  application:
    name: image
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 60
    height: 60
  tracker-list[0]: 192.168.29.200:22122 # tracker地址
